""" Django settings for backend project.
Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-wlghq^@ig17w!9u4n+magq#3kgfhe)yn3a&1!6+n8dxxqo1e_%"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
ADDITIONAL_APPS = [
    "backend.apps.users",
    "backend.apps.products",
    "backend.apps.auth",
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "rest_framework_simplejwt",
    "storages",
]

INSTALLED_APPS += ADDITIONAL_APPS

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "backend" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "MinimumLengthValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "CommonPasswordValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "NumericPasswordValidator"),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# STATIC & MEDIA (Local defaults)
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "/static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# AWS Credentials
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "test")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "test")
AWS_REGION_NAME = os.getenv("AWS_REGION_NAME", "us-east-1")
AWS_ENDPOINT_URL = os.getenv("AWS_ENDPOINT_URL", "http://localhost:4566")

# -------------------------
# LocalStack / S3 Settings
# -------------------------
USE_S3 = os.getenv("USE_S3", "false").upper() == "TRUE"

AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_S3_BUCKET_NAME", "test-bucket")

# Required for LocalStack — ensures URL works
AWS_S3_ADDRESSING_STYLE = "path"
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_QUERYSTRING_AUTH = False

if USE_S3:
    # LocalStack asset base url
    AWS_S3_BUCKET_BASE_URL = f"http://{AWS_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}"

    STATIC_URL = f"{AWS_S3_BUCKET_BASE_URL}/static/"
    MEDIA_URL = f"{AWS_S3_BUCKET_BASE_URL}/media/"

    STORAGES = {
        "default": {
            "BACKEND": "backend.apps.core.storage.PublicMediaStorage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "region_name": AWS_REGION_NAME,
                "endpoint_url": AWS_ENDPOINT_URL,
                "default_acl": "public-read",
                "file_overwrite": False,
            },
        },
        "staticfiles": {
            "BACKEND": "backend.apps.core.storage.StaticMediaStorage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "region_name": AWS_REGION_NAME,
                "endpoint_url": AWS_ENDPOINT_URL,
                "default_acl": "public-read",
                "file_overwrite": True,
            },
        },
    }
else:
    STATIC_URL = "/static/"
    STATIC_ROOT = BASE_DIR / "staticfiles"

    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"

# -------------------------
# LocalStack / SES Settings
# -------------------------

EMAIL_BACKEND = "django_ses.SESBackend"

ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "test@email.com")

# LocalStack endpoints
AWS_SES_REGION_NAME = AWS_REGION_NAME
AWS_SES_REGION_ENDPOINT_URL = AWS_ENDPOINT_URL
AWS_SES_AUTO_THROTTLE = 0  # 🔥 IMPORTANT
USE_SES_V2 = False

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Celery
CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL", "amqp://guest:guest@localhost:5672//"
)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60
CELERY_RESULT_EXPIRES = 3600

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "backend.apps.core.pagination.DefaultPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Local Cloud API",
    "DESCRIPTION": "API for Local Cloud application",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

AWS_CLOUDWATCH_LOG_GROUP = os.getenv("AWS_CLOUDWATCH_LOG_GROUP", 'django-local-logs"')
AWS_CLOUDWATCH_STREAM_NAME = os.getenv("AWS_CLOUDWATCH_STREAM_NAME", "app-stream")

LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
CLOUD_WATCH_LOG_LEVEL = os.getenv("CLOUD_WATCH_LOG_LEVEL", "WARNING")

LOG_DIR = BASE_DIR / "logs"
os.makedirs(LOG_DIR, exist_ok=True)

CLOUD_WATCH_ENABLED = os.getenv("CLOUD_WATCH_ENABLED", "false").upper() == "TRUE"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "app.log"),
            "formatter": "standard",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
            "propagate": True,
        },
        "backend": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
            "propagate": True,
        },
    },
}

if CLOUD_WATCH_ENABLED:
    LOGGING["handlers"]["cloudwatch"] = {
        "level": CLOUD_WATCH_LOG_LEVEL,
        "class": "backend.apps.core.logger.cloudwatch.LocalStackHandler",
        "formatter": "standard",
    }
    LOGGING["loggers"]["django"]["handlers"].append("cloudwatch")
    LOGGING["loggers"]["backend"]["handlers"].append("cloudwatch")

PROJECT_PREFIX = os.getenv("PROJECT_PREFIX", "local-cloud")
