# Generated by Django 5.2.8 on 2025-12-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quota",
                    models.IntegerField(
                        default=1000, help_text="Maximum number of products allowed"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Settings",
                "verbose_name_plural": "Product Settings",
            },
        ),
    ]
